### ISSUE TITLE
[Request] is it possible to connect to an ip instead of local tty?

### ISSUE THREAD

**Issue by zuidwijk** [mweimerskirch/smarty_dsmr_proxy#5]
I wonder if your code could be used to connect to ip devices (like esp-link).
And than mapping that to a local pseudo tty.

`[Ip device]——[decryptor.py wrapper]——[local tty]`

So the other way around 😁

**Comment by haklein** [comment]
That should be achievable with socat, providing a "virtual" serial port for smarty_dsmr_proxy to read from

**Comment by zuidwijk** [comment]
> That should be achievable with socat, providing a "virtual" serial port for smarty_dsmr_proxy to read from

Yeah I know, I just couldn't figure it out (yet :) )

**Comment by mweimerskirch** [comment]
Closing this, as I suppose this is no longer needed?
Personally, I have migrated to your ESPHome based solution which also supports the encryption (https://www.zuidwijk.com/product/slimmelezer/) a few weeks ago and found that much easier to maintain. Thank you for that.
