### ISSUE TITLE
add parsing via dsmr_parser, add MQTT

### ISSUE THREAD

**Issue by haklein** [mweimerskirch/smarty_dsmr_proxy#7]
Are there any plans to add parsing (e.g. via dsmr_parser) and add optional MQTT support? I was wondering if such pull requests would be accepted, or if this would go beyond the scope of the project..

**Comment by haklein** [comment]
The parser works pretty handy for me, e.g. a pretty print of the telegram:
~~~
from dsmr_parser import telegram_specifications
from dsmr_parser.parsers import TelegramParser
from dsmr_parser import obis_references
from dsmr_parser import obis_name_mapping

parser = TelegramParser(telegram_specifications.V5)
telegram = parser.parse(decryption.decode())
for key in telegram:
    print("%s: %s" % (obis_name_mapping.EN[key], telegram[key]))
~~~

**Comment by haklein** [comment]
MQTT works perfect via the paho library, that would only need some command line options and a few lines of code

**Comment by mweimerskirch** [comment]
No plans from my side because of timing constraints, but I would be interested in using this myself, so I would definitely accept such a PR.
