### ISSUE TITLE
AAD should be configurable

### ISSUE THREAD

**Issue by arno82** [mweimerskirch/smarty_dsmr_proxy#8]
The AAD is not fixed to 3000112233445566778899AABBCCDDEEFF in Austria for Sagemcom T210 smart meters.
Normally this AAD value is delivered as PDF together with the main key (Global Unicast Encryption Key GUEK).
AAD is named Global Authentication Key (GAK).

Thus this value should be configurable.

**Comment by haklein** [comment]
Great finding @arno82, I can confirm that this works for me, too (30 + GAK_SM_CI_128)
